# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: downloader/downloader.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from proto.types import types_pb2 as types_dot_types__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1b\x64ownloader/downloader.proto\x12\ndownloader\x1a\x1bgoogle/protobuf/empty.proto\x1a\x11types/types.proto\"?\n\x0c\x44ownloadItem\x12\x0c\n\x04path\x18\x01 \x01(\t\x12!\n\x0ctorrent_hash\x18\x02 \x01(\x0b\x32\x0b.types.H160\":\n\x0f\x44ownloadRequest\x12\'\n\x05items\x18\x01 \x03(\x0b\x32\x18.downloader.DownloadItem\"\x0f\n\rVerifyRequest\"\x0e\n\x0cStatsRequest\"\xe1\x01\n\nStatsReply\x12\x15\n\rmetadataReady\x18\x01 \x01(\x05\x12\x12\n\nfilesTotal\x18\x02 \x01(\x05\x12\x13\n\x0bpeersUnique\x18\x04 \x01(\x05\x12\x18\n\x10\x63onnectionsTotal\x18\x05 \x01(\x04\x12\x11\n\tcompleted\x18\x06 \x01(\x08\x12\x10\n\x08progress\x18\x07 \x01(\x02\x12\x16\n\x0e\x62ytesCompleted\x18\x08 \x01(\x04\x12\x12\n\nbytesTotal\x18\t \x01(\x04\x12\x12\n\nuploadRate\x18\n \x01(\x04\x12\x14\n\x0c\x64ownloadRate\x18\x0b \x01(\x04\x32\xcb\x01\n\nDownloader\x12\x41\n\x08\x44ownload\x12\x1b.downloader.DownloadRequest\x1a\x16.google.protobuf.Empty\"\x00\x12=\n\x06Verify\x12\x19.downloader.VerifyRequest\x1a\x16.google.protobuf.Empty\"\x00\x12;\n\x05Stats\x12\x18.downloader.StatsRequest\x1a\x16.downloader.StatsReply\"\x00\x42\x19Z\x17./downloader;downloaderb\x06proto3')



_DOWNLOADITEM = DESCRIPTOR.message_types_by_name['DownloadItem']
_DOWNLOADREQUEST = DESCRIPTOR.message_types_by_name['DownloadRequest']
_VERIFYREQUEST = DESCRIPTOR.message_types_by_name['VerifyRequest']
_STATSREQUEST = DESCRIPTOR.message_types_by_name['StatsRequest']
_STATSREPLY = DESCRIPTOR.message_types_by_name['StatsReply']
DownloadItem = _reflection.GeneratedProtocolMessageType('DownloadItem', (_message.Message,), {
  'DESCRIPTOR' : _DOWNLOADITEM,
  '__module__' : 'downloader.downloader_pb2'
  # @@protoc_insertion_point(class_scope:downloader.DownloadItem)
  })
_sym_db.RegisterMessage(DownloadItem)

DownloadRequest = _reflection.GeneratedProtocolMessageType('DownloadRequest', (_message.Message,), {
  'DESCRIPTOR' : _DOWNLOADREQUEST,
  '__module__' : 'downloader.downloader_pb2'
  # @@protoc_insertion_point(class_scope:downloader.DownloadRequest)
  })
_sym_db.RegisterMessage(DownloadRequest)

VerifyRequest = _reflection.GeneratedProtocolMessageType('VerifyRequest', (_message.Message,), {
  'DESCRIPTOR' : _VERIFYREQUEST,
  '__module__' : 'downloader.downloader_pb2'
  # @@protoc_insertion_point(class_scope:downloader.VerifyRequest)
  })
_sym_db.RegisterMessage(VerifyRequest)

StatsRequest = _reflection.GeneratedProtocolMessageType('StatsRequest', (_message.Message,), {
  'DESCRIPTOR' : _STATSREQUEST,
  '__module__' : 'downloader.downloader_pb2'
  # @@protoc_insertion_point(class_scope:downloader.StatsRequest)
  })
_sym_db.RegisterMessage(StatsRequest)

StatsReply = _reflection.GeneratedProtocolMessageType('StatsReply', (_message.Message,), {
  'DESCRIPTOR' : _STATSREPLY,
  '__module__' : 'downloader.downloader_pb2'
  # @@protoc_insertion_point(class_scope:downloader.StatsReply)
  })
_sym_db.RegisterMessage(StatsReply)

_DOWNLOADER = DESCRIPTOR.services_by_name['Downloader']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\027./downloader;downloader'
  _DOWNLOADITEM._serialized_start=91
  _DOWNLOADITEM._serialized_end=154
  _DOWNLOADREQUEST._serialized_start=156
  _DOWNLOADREQUEST._serialized_end=214
  _VERIFYREQUEST._serialized_start=216
  _VERIFYREQUEST._serialized_end=231
  _STATSREQUEST._serialized_start=233
  _STATSREQUEST._serialized_end=247
  _STATSREPLY._serialized_start=250
  _STATSREPLY._serialized_end=475
  _DOWNLOADER._serialized_start=478
  _DOWNLOADER._serialized_end=681
# @@protoc_insertion_point(module_scope)
